<?php

require_once(drupal_get_path('module', 'commerce_cardgate') . '/cardgate/base.php');

function commerce_cardgate_onlineueberweisen_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods = array();

  $genericdata = commerce_payment_method_instance_load('generic|commerce_payment_generic');
  $checkoutview = (isset($genericdata['settings']['checkoutview']) ? $genericdata['settings']['checkoutview'] : 'text');
  $genericdata = null;

  $title = t('OnlineÜberweisen');
  $img = _cggetImage('onlineueberweisen.svg');

 switch ($checkoutview){
 	case 'logos':
		$display_title = $img;
		break;
	case 'text':
		$display_title = $title;
		break;
	case 'logosandtext':
		$display_title = $img.' '.$title;
  		break;
  }

  $payment_methods['onlineueberweisen'] = array(
    'base' => 'commerce_cardgate_onlineueberweisen',
    'title' => $title,
    'short_title' => t('OnlineÜberweisen'),
    'display_title' => $display_title,
    'description' => t('OnlineÜberweisen betaling'),
    'terminal' => TRUE,
    'offsite' => TRUE,
    'offsite_autoredirect' => TRUE,
  );

  return $payment_methods;
}

function commerce_cardgate_onlineueberweisen_settings_form($settings = NULL) {
	$form = _cgsettings($settings, 'commerce_cardgate_onlineueberweisen_', 'onlineueberweisen');
	$form['currency_code'] = array(
		'#type' => 'select',
		'#title' => t('Currency'),
		'#description' => t('Transactions can only be processed in one of the listed currencies.'),
		'#options' => commerce_cardgate_onlineueberweisen_currencies(),
		'#default_value' => (empty($settings['currency_code'])? '':$settings['currency_code']),
	);

	return $form;
}

function commerce_cardgate_onlineueberweisen_redirect_form($form, &$form_state, $order, $payment_method)
{
    _cgbetaling($order, $payment_method) ;
}

/**
 * Returns an array of all possible language codes.
 */
function commerce_cardgate_onlineueberweisen_languages() {
  return drupal_map_assoc(array('AU', 'DE', 'FR', 'IT', 'GB', 'ES', 'US'));
}

/**
 * Returns an array of all possible currency codes.
 */
function commerce_cardgate_onlineueberweisen_currencies() {
  return drupal_map_assoc(array('EUR', 'GBP', 'USD'));
}
