<?php
/**
 * CURO Payments
 *
 * @author CURO Payments
 * @package clientlib config
 * @version 1.0
 *
 * == BEGIN LICENSE ==
 *
 * THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
 * OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * == END LICENSE ==
 */

// Enter your API credentials provided by CURO Payments.
// $aConfig['merchant_id'] = '1001';
// $aConfig['merchant_secret'] = 'MYS1OohIeZoTJGb1N7ty1Wq8VJPCgpcz7WNKPHO9gM1tUcHRACXeqB0NV8oNqa4u';
$aConfig['merchant_id'] = '1066';
$aConfig['merchant_secret'] = 'TuZFZq6K2bPBi7VTkQNYM3JFlD21wz8tQ0sNCqODTZxJWKScRlVm366GaRoIlIdQ';

// Set testmode to TRUE for testing and debugging.
$aConfig['testmode'] = TRUE;