<?php

require_once(drupal_get_path('module', 'commerce_cardgate') . '/cardgate/base.php');

/**
 * Implements hook_menu().
 */
function commerce_cardgate_menu() {
  $items = array();

  // Define an always accessible path to receive IPNs.
  $items['commerce_cardgate/notify'] = array(
    'page callback' => 'commerce_cardgate_process_notify',
    'page arguments' => array(),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  // Define an additional IPN path that is payment method / instance specific.
  $items['commerce_cardgate/notify/%commerce_payment_method_instance'] = array(
    'page callback' => 'commerce_cardgate_process_notify',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Returns the IPN URL.
 *
 * @param $method_id
 *   Optionally specify a payment method ID to include in the URL.
 */
function commerce_cardgate_notify_url($method_id = NULL) {
  $parts = array(
    'commerce_cardgate',
    'notify',
  );

  if (!empty($method_id)) {
    $parts[] = $method_id;
  }

  return url(implode('/', $parts), array('absolute' => TRUE));
}

/**
 * Processes an incoming IPN.
 *
 * @param $payment_method
 *   The payment method instance array that originally made the payment.
 * @param $debug_ipn
 *   Optionally specify an IPN array for debug purposes; if left empty, the IPN
 *     be pulled from the $_POST. If an IPN is passed in, validation of the IPN
 *     at PayPal will be bypassed.
 *
 * @return
 *   TRUE or FALSE indicating whether the IPN was successfully processed or not.
 */
function commerce_cardgate_process_notify($payment_method) 
{
        $trxid = $_REQUEST['transaction'];
        $reference = $_REQUEST['reference'];
        //split reference to obtain orderid
        $aReference = explode('_',$reference);
        $orderid = $aReference[1];
  	_cgnotify($trxid, $orderid, $payment_method);
}

/**
 * Returns an array of PayPal payment method icon img elements.
 *
 * @return
 *   The array of themed payment method icons keyed by name: visa, mastercard,
 *   amex, discover, echeck, paypal
 */
function commerce_cardgate_icons() {
  $icons = array();

  $payment_methods = array(
    'afterpay' => t('Afterpay'),
    'banktransfer' => t('Bankoverboeking'),
    'creditcard' => t('CreditCard'),
    'directdebit' => t('Incasso'),
    'giropay' => t('Giropay'),
    'ideal' => t('iDEAL'),
    'mistercash' => t('MisterCash'),
    'paypal' => t('PayPal'),
    'sofort' => t('SOFORTbanking')
  );

  foreach ($payment_methods as $name => $title) {
    $variables = array(
      'path' => drupal_get_path('module', 'commerce_cardgate') . '/images/' . $name . '.gif',
      'title' => $title,
      'alt' => $title,
      'attributes' => array(
        'class' => array('commerce-paypal-icon'),
      ),
    );
   // $icons[$name] = theme('image', $variables);
  }

  return $icons;
}
