<?php

require_once(drupal_get_path('module', 'commerce_cardgate') . '/cardgate/base.php');

function commerce_cardgate_sofortpay_commerce_payment_method_info() {
    if (!currency_check('cardgatesofortpay')) return [];

  $payment_methods = array();

  $genericdata = commerce_payment_method_instance_load('generic|commerce_payment_generic');
  $checkoutview = (isset($genericdata['settings']['checkoutview']) ? $genericdata['settings']['checkoutview'] : 'text');
  $genericdata = null;

  $title = t('SofortPay');
  $img = _cggetImage('sofortpay.svg');

 switch ($checkoutview){
 	case 'logos':
		$display_title = $img;
		break;
	case 'text':
		$display_title = $title;
		break;
	case 'logosandtext':
		$display_title = $img.' '.$title;
  		break;
  }

  $payment_methods['sofortpay'] = array(
    'base' => 'commerce_cardgate_sofortpay',
    'title' => $title,
    'short_title' => t('SofortPay'),
    'display_title' => $display_title,
    'description' => t('SofortPay betaling'),
    'terminal' => FALSE,
    'offsite' => TRUE,
    'offsite_autoredirect' => TRUE,
  );

  return $payment_methods;
}

function commerce_cardgate_sofortpay_settings_form($settings = NULL) {
	$form = _cgsettings($settings, 'commerce_cardgate_sofortpay_', 'sofortpay');

	$form['currency_code'] = array(
		'#type' => 'select',
		'#title' => t('Currency'),
		'#description' => t('Transactions can only be processed in one of the listed currencies.'),
		'#options' => commerce_cardgate_sofortpay_currencies(),
		'#default_value' =>(empty($settings['currency_code'])? '':$settings['currency_code']),
	);

	return $form;
}

function commerce_cardgate_sofortpay_redirect_form($form, &$form_state, $order, $payment_method)
{
	_cgbetaling($order, $payment_method) ;
}

/**
 * Returns an array of all possible language codes.
 */
function commerce_cardgate_sofortpay_languages() {
  return drupal_map_assoc(array('AU', 'DE', 'FR', 'IT', 'GB', 'ES', 'US'));
}

/**
 * Returns an array of all possible currency codes.
 */
function commerce_cardgate_sofortpay_currencies() {
  return drupal_map_assoc(array('EUR', 'GBP', 'USD'));
}
